### ISSUE TITLE
Transactions summary

### ISSUE THREAD

**Issue by ruiglopes** [srMarquinho/ultimate-dividend-portfolio#10]
On 1.1.1 transactions summary is not adding the lines as it should. Identifies correctly the number of transactions however, it doesn't seem to add properly all of them. I've seen the issue mostly on the "Sold" addition.

**Comment by srMarquinho** [comment]
Is it since 1.1.1 only?
Have you tried a hard refresh? Clearing cache etc?
If so, would you mind sending an example?

**Comment by ruiglopes** [comment]
Updated from 1.0.1 to 1.1.1 and it was working correctly before. Tried a hard refresh and different laptop/browser. 

Screenshots 1.0.1 vs 1.1.1 attached.

![101](https://user-images.githubusercontent.com/59895610/85277911-1b964a00-b47c-11ea-8d10-8ac619a1a6eb.png)
![111](https://user-images.githubusercontent.com/59895610/85277916-1c2ee080-b47c-11ea-889d-78d7bc350a65.png)

**Comment by srMarquinho** [comment]
Thanks for reporting @ruiglopes 
Could you try 1.1.2 and let me know, please?

**Comment by ruiglopes** [comment]
It's fixed! Thanks !
